project:
  type: book

book:
  title: "Group13 Reproducible Study"
  author: "Group 13"
  date: now
  chapters:
    - index.qmd
    - one.qmd
    - two.qmd
    - Correlation analysis and significance of gene expression and pseudo-temporal trajectory.qmd        
    - four.qmd
    - five.qmd


format:
  html:
    theme: cosmo



